// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package proto.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
