// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package proto.grpc;

public final class HelloMessage {
  private HelloMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_grpc_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_grpc_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\nproto.grpc\"\034\n\014HelloReques" +
      "t\022\014\n\004name\030\001 \001(\t\" \n\rHelloResponse\022\017\n\007mess" +
      "age\030\001 \001(\t2\277\002\n\005Hello\022A\n\010sayHello\022\030.proto." +
      "grpc.HelloRequest\032\031.proto.grpc.HelloResp" +
      "onse\"\000\022O\n\024sayHelloClientStream\022\030.proto.g" +
      "rpc.HelloRequest\032\031.proto.grpc.HelloRespo" +
      "nse\"\000(\001\022O\n\024sayHelloServerStream\022\030.proto." +
      "grpc.HelloRequest\032\031.proto.grpc.HelloResp" +
      "onse\"\0000\001\022Q\n\024sayHelloDoubleStream\022\030.proto" +
      ".grpc.HelloRequest\032\031.proto.grpc.HelloRes" +
      "ponse\"\000(\0010\001B\034\n\nproto.grpcB\014HelloMessageP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_proto_grpc_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_grpc_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_grpc_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
